name: PPS DAMA Workflow
on:
  push:
  pull_request:
jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      TERM: dumb
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: joschi/setup-jdk@v2.3.0
        with:
          java-version: 11
      - name: Build
        run: ./gradlew build
      - uses: actions/checkout@master
      - uses: codecov/codecov-action@v2
        with:
          files: ./coverage1.xml,./coverage2.xml # optional
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
